### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by ShamilTim** [ShamilTim/sellers-workplace#1]
@coursar
Прошу проверить ДЗ

**Comment by coursar** [comment]
Всё ок, только желательно не хранить всё в одном каталоге, а положить в package.

**Comment by ShamilTim** [comment]
@coursar выполнил размещение проекта в packages, в соответствии с рекомендациями в книге Flask Web Development by Miguel Grinberg.
Всё ли я сделал корректно?
